version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "4000:3000"
    links:
      - mysql-server
    networks:
      - pentester
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: security
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pentester
    ports:
      - "3306:3306"

networks:
  pentester:
    driver: bridge