version: '3.8'
services:
  mysql:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: security
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  app:
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    image: backend_api
    depends_on:
      - mysql
    ports:
      - "3000:3000"